version: '3.1'
services:
  zoo1:
    image: 'zookeeper:3.9.0'
    container_name: 'zookeeper_zoo1'
    restart: 'always'
    hostname: zoo1
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_TICK_TIME: 2000 # tickTime=2000
      ZOO_INIT_LIMIT: 20 # initLimit=20
      ZOO_SYNC_LIMIT: 5 # syncLimit=5
    volumes:
      - ./volume/zookeeper/zoo1/data:/data
      - ./volume/zookeeper/zoo1/datalog:/data
  zoo2:
    image: 'zookeeper:3.9.0'
    container_name: 'zookeeper_zoo2'
    restart: 'always'
    hostname: zoo2
    ports:
      - '2182:2181'
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_TICK_TIME: 2000 # tickTime=2000
      ZOO_INIT_LIMIT: 20 # initLimit=20
      ZOO_SYNC_LIMIT: 5 # syncLimit=5
    volumes:
      - ./volume/zookeeper/zoo2/data:/data
      - ./volume/zookeeper/zoo2/datalog:/data
  zoo3:
    image: 'zookeeper:3.9.0'
    container_name: 'zookeeper_zoo3'
    restart: 'always'
    hostname: zoo3
    ports:
      - '2183:2181'
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_TICK_TIME: 2000 # tickTime=2000
      ZOO_INIT_LIMIT: 20 # initLimit=20
      ZOO_SYNC_LIMIT: 5 # syncLimit=5
    volumes:
      - ./volume/zookeeper/zoo3/data:/data
      - ./volume/zookeeper/zoo3/datalog:/data
  kafka:
    image: 'confluentinc/cp-kafka:7.5.0.arm64'
    container_name: 'kafka'
    restart: 'always'
    depends_on:
      - 'zoo1'
      - 'zoo2'
      - 'zoo3'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKDER_ID: 1 # 1. broker.id, 정숫값 식별자
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093 # 2. listeners, 단순한 port 설정 지원 중단
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 # 일반적인 보안 프로토콜이 아님
      KAFKA_ZOOKEEPER_CONNECT: 'zoo1:2181,zoo2:2182,zoo3:2183' # 3. zookeeper.connect
      LOG_DIRS: '/tmp/logs' # 4. log.dirs
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1 # 5. num.recovery.threads.per.data.dir
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false' # 6. auto.create.topics.enable
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 70  # 7. auto.leader.rebalance.enable
      KAFKA_DELETE_TOPIC_ENABLE: 'false' # 8. delete.topic.enable
    volumes:
      - ./volume/kafka/data:/var/lib/kafka/data
      - ./volume/kafka/logs:/tmp/logs