mkdir ./volume
mkdir ./volume/zookeeper
mkdir ./volume/zookeeper/zoo1
mkdir ./volume/zookeeper/zoo2
mkdir ./volume/zookeeper/zoo3
mkdir ./volume/kafka
mkdir ./volume/kafka/data
mkdir ./volume/kafka/logs
mkdir ./volume/mongo
